
osc=no
input-default-bindings=yes
input-conf=~/.config/mpv/input.conf

# Resume playback position when quitting and reopening
save-position-on-quit=yes

# Automatically load the last file
loadfile=last
