# ─────────────────────────────
# ⏩ Scene/Chapter Navigation
# ─────────────────────────────
Alt+z add chapter +1        # Jump to next scene/chapter
Alt+Shift+z add chapter -1  # Jump to previous scene/chapter

# ─────────────────────────────
# 🎥 Playback Controls
# ─────────────────────────────
space cycle pause            # Play/Pause
left seek -10                # Back 10s
right seek 8                # Forward 10s
shift+left seek -3              # Fine rewind (3s)
shift+right seek 3      
ctrl+left seek  -60
ctrl+right seek 60
 


# ─────────────────────────────
# 🔊 Volume & Playback Speed
# ─────────────────────────────
up add volume 5              # Volume up
down add volume -5           # Volume down
= add speed 0.1              # Increase playback speed
- add speed -0.1             # Decrease playback speed
0 set speed 1.0              # Reset playback speed


# ─────────────────────────────
# 🎧 Audio & 🈳 Subtitle Tracks
# ─────────────────────────────
b cycle audio                # Next audio track
v cycle sub                  # Next subtitle track
c cycle sub down
ctrl+d  script-binding uosc/download-subtitles  #+ Subtitles > Download
ctrl+= add sub-scale +0.1                  # increase subtitle font size
ctrl+- add sub-scale -0.1                  # decrease subtitle font size
ctrl+` script-message copy-clipboard ${sub-text}

# z cycle sub none        # Toggle subtitles on/off
# x cycle audio none      # Toggle audio on/off

mbtn_right  script-binding uosc/menu
alt+c script-binding uosc/subtitles
alt+b script-binding uosc/audio


########################
t script-message-to uosc flash-elements timeline,speed

############################

] script-binding uosc/next
[ script-binding uosc/prev

###################################

BS seek 0 absolute   