osd-bar=no
border=no
video-sync=display-resample
input-default-bindings=yes

# Enable auto-resume functionality
save-position-on-quit=yes

# Change subtitle font to Segoe UI
sub-font="Segoe UI"

keep-open

volume-max=200

sub-font="Segoe UI bold"
sub-font-size=53


sub-color="#FFFFFF"
sub-border-color="#000000"

sub-pos=100.5
